repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/tomcatling/black-nb
    rev: "0.7"
    hooks:
      - id: black-nb
        args: [--verbose, --clear-output]
